spring:
  datasource:
    url: jdbc:mysql://82.157.64.59:3307/spider_net?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: zhang1998
    hikari:
      max-lifetime: 120000
      connection-init-sql: SET sql_mode ='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
    driver-class-name: com.mysql.cj.jdbc.Driver
